name: communication-test2

on: workflow_dispatch

jobs: 
    build-metrics: 
        runs-on: ubuntu-22.04
        steps: 
            - uses: actions/checkout@v4

            - name: Run the model metrics
              run: python metrics.py

            - name: Upload artifacts
              uses: actions/upload-artifact@v4 
              with: 
                name: model-metrics 
                path: metrics.json 